### ISSUE TITLE
Add support for Frosting

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#129]
As in https://github.com/cake-build/cake-vs/issues/112, Rider should also support Cake.Frosting

**Comment by nils-a** [comment]
Project template support is available, since #139.

Todo seems to be:
* [ ] Live-Templates (snippets)
* [ ] Run configurations

And dditionally:
* [ ] check whether the *Cake Tasks window* can list Frosting projects and tasks
* [ ] check whether it is possible to extend the *Structure View* of `.cs` files to list tasks (using `com.intellij.ide.structureView.StructureViewExtension`)
* [ ] check whether it is possible to show the code-hints to run a task in a `*.cs` file of a frosting project, as in `*.cake` files.

**Comment by js6pak** [comment]
> Run configurations

What would a run configuration for a cake frosting project be?
Should it just extend the .net project configuration with additional target option (that would just pass `--target`)? Assuming its even possible when all rider classes are final, eventually just make a clone.

For context this how .net project run configuration looks:
![image](https://user-images.githubusercontent.com/35262707/183221354-56d00da2-c7ec-488c-96ff-ffa7af289dab.png)

**Comment by nils-a** [comment]
I would rather expect the dialog to look exactly like the Cake dialog. Only the "picker" that is called *script path* should be called *build project path* or something like that. 

And during execution it should do `dotnet run -- <all arguments>` instead of `dotnet cak <all arguments>`

**Comment by nils-a** [comment]
Closing this issue, as possibilities have been evaluated and follow-up tasks were created in #264, #263, #262 and #261
