### ISSUE TITLE
Decide where to continue the documentation

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#29]
possible options include:
* in `Readme.md`
* in the `Integrations` section of https://cakebuild.net/
* in this repository, in markdown, wyam generated to `gh-pages`

**Comment by nils-a** [comment]
Currently `Readme.md` contains the "truth". When https://github.com/cake-build/website/pull/1441 is merged the whole documentation will be in `cake-build/website`, too. (Though structured a bit differently)

It's kind of lightweight to have docs "here" (as opposed to over at `cake-build/website`) for modifications. Then again, to have the official documentation in the official website also has it's benefits. 

So, I think the *real cool way* would be to have the docs here, in markdown and on publish do an (automatic) PR into `cake-build/website`
Alternatively I can imagine to have the documentation of the current/stable version in `cake-build/website` (and a reference to that documentation here) and then only track the newest changes here (in markdown). On release I would PR the changes manually into `cake-build/website` and remove them here.

@gep13 @pascalberger @anna-dolbina  thoughts?

**Comment by gep13** [comment]
As long as we can avoid duplication of effort in updating, I would be all for any suggestions.

The reason that we have done what we have for the other extensions is that a source file is required for the marketplace directly.  So we have trimmed that down where possible, adn linked to the official docs on the website for other things.

**Comment by nils-a** [comment]
I see. The JB Marketplace has custom "pages" for that. You can create as many as you like (read: I've seen no obvious limit, there.) 

I was thinking to create a very simple page there to contain the main links. I.e. cakebuild.net. this repo, issues, docs something like this.

let's wait if someone has other ideas, but I think I would plan on having the official docs in `cake-build/website` and move them from here to there somehow. (That is: manually at first, but ideally that should be automatic somehow)

**Comment by pascalberger** [comment]
We already have integration from different repos into website. E.g. https://cakebuild.net/community/cake-contrib comes from https://github.com/cake-contrib/Home/blob/master/README.md and https://cakebuild.net/community/contributing/contribution-guidelines comes from https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md. This is done by cloning the corresponding repositories during build of the website and referencing the files from these repos. 

We can use the same approach to pull in documentation from this repo, but I doubt that a repo README will ever be a good fit to put 1:1 into website documentation.

**Comment by nils-a** [comment]
Ok.
I'll update the readme here to point at the documentation at https://cakebuild.net/docs/integrations/editors/rider/ 

For modifications we will keep the "changes" to the documentation here and after/with a release will do a PR into https://github.com/cake-build/website

Until we find a more automated solution 😄
