### ISSUE TITLE
Add file-icons

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#30]
currently *.cake scripts have default icons.
![image](https://user-images.githubusercontent.com/349188/103547727-155e3d00-4ea5-11eb-81c4-37f5b983c9e3.png)

They should have little cake-icons.

@gep13 
Cake-VsCode uses "red" icons:
![image](https://user-images.githubusercontent.com/349188/103547885-4179be00-4ea5-11eb-98f6-383e37f6221e.png)

While Cake-Vs uses the "normal" icons:
![image](https://user-images.githubusercontent.com/349188/103548717-818d7080-4ea6-11eb-8d68-db89ca7a1064.png)

I'd like the the same as Cake-Vs (i.e. the default Cake icon). Any objections to that?

**Comment by gep13** [comment]
VsCode also has the option to use the actual icon, just with a different theme:

![image](https://user-images.githubusercontent.com/1271146/103550830-62d8ab00-4ea1-11eb-8b6a-843197831390.png)

Ideally, it would be the "actual" icon that is used.
