### ISSUE TITLE
Upgrade Rider to 2023.2

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#355]
~~This is currently blocked by #32~~

**Comment by brumlemann** [comment]
Typical. Exactly when I needed to do some work on Cake build scripts there's a version mismatch :-(

@nils-a Big breaking change or can we expect support for 2023.2 shortly?

**Comment by nils-a** [comment]
@brumlemann I /think/ all problems have been solved, and only some more tests are needed. There are some breaking changes to the 2023.2 api, so the next version of Cake for Rider will probably support 2023.2 only.

Giving an estimation, of how long it will take, is always problematic: Everyone in the Cake team has a day-job, a life and a family. What's left will be individually divided into multiple OSS projects.
Rest assured that we're all working as hard as we can.
