### ISSUE TITLE
Can't use plugin on macOS

### ISSUE THREAD

**Issue by DamianAntonowicz** [cake-build/cake-rider#48]
I receive following error when I try to use plugin on macOS:

"Error running 'build.cake: Clean':
Cannot run program "dotnet-cake" (in directory "xxx): error=2, No such file or directory"

What am I missing? :)

**Comment by nils-a** [comment]
@DamianAntonowicz Did follow the [docs](https://cakebuild.net/docs/integrations/editors/rider/run-configurations#configuring-run-configurations) and install the cake .NET tool? Or are you using another Cake runner?

**Comment by DamianAntonowicz** [comment]
@nils-a executing `dotnet tool install --global Cake.Tool` and adding "xxx/.dotnet/tools" to PATH env helped. Thanks!

**Comment by nils-a** [comment]
@DamianAntonowicz is it "normal" to add the tools path to the .NET global tools manually on Mac?

**Comment by DamianAntonowicz** [comment]
@nils-a output from mentioned command told it needs to be done manually :)

**Comment by gep13** [comment]
>@nils-a said...
is it "normal" to add the tools path to the .NET global tools manually on Mac?

I haven't normally had to do this, no.

**Comment by nils-a** [comment]
@gep13 since @DamianAntonowicz said 

>  output from mentioned command told it needs to be done manually

I feel it's related to dotnet tools installation and hence need not explicitly mentioned in the docs here.
