### ISSUE TITLE
Passing custom arguments

### ISSUE THREAD

**Issue by DamianAntonowicz** [cake-build/cake-rider#49]
Is it possible to pass custom arguments to Cake script from Run Configuration? I've checked https://cakebuild.net/docs/integrations/editors/rider/run-configurations#creating-run-configurations but didn't find a way to do it. I would like to pass custom argument to my script.

**Comment by nils-a** [comment]
@DamianAntonowicz It's currently not possible - I'll add it to the 0.2.0 milestone.

**Comment by nils-a** [comment]
@DamianAntonowicz the version 0.2.0 is available now. If you update the plugin in Rider you will be able to pass custom arguments.

**Comment by DamianAntonowicz** [comment]
@nils-a I don't see field for "Arguments" in configuration editor:
![Screenshot 2021-02-01 at 17 43 30](https://user-images.githubusercontent.com/12022141/106489418-0b842580-64b5-11eb-98d0-5e84bc5198a6.png)

I'm using 0.2.0 version of plugin. What am I missing?

**Comment by gep13** [comment]
That is very strange. If you look at the video I did here: Cake Extension for Rider Release 0.2.0 https://youtu.be/yA73I4Ky87s around the 2:20 mark, you will see the Arguments input box.

**Comment by DamianAntonowicz** [comment]
@gep13 I'm using Rider on macOS. Could this be an issue?

**Comment by gep13** [comment]
Short answer... I don't know. I may be in a position to test this a little later this evening. I will post back here when I can verify.

**Comment by augustoproiete** [comment]
@DamianAntonowicz Are you sure you updated to 0.2.0 (**and clicked "Save"**)?

This is 0.2.0 on OSX right now:

![image](https://user-images.githubusercontent.com/177608/106500143-dae1c300-6497-11eb-909a-1edc4be70f70.png)

![image](https://user-images.githubusercontent.com/177608/106500170-e46b2b00-6497-11eb-9ccc-957177a80b12.png)

**Comment by DamianAntonowicz** [comment]
The problem was that I was using Rider 2020.2.4. After upgrading to 2020.3.2 I can see "Arguments" field.
