### ISSUE TITLE
gitter / twitter messages contain a typo

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-rider#67]
![image](https://user-images.githubusercontent.com/349188/104970625-6bc29400-59ec-11eb-8a4e-22afd48e2b98.png)

![image](https://user-images.githubusercontent.com/349188/104970642-7a10b000-59ec-11eb-944a-4cb4ad83e2ad.png)

**Comment by nils-a** [comment]
Also, we changed the "display name" from ~cake-rider~ to *Cake for Rider*.

**Comment by pascalberger** [comment]
For the typo fix see https://github.com/cake-contrib/Cake.IntelliJ.Recipe/pull/26

**Comment by nils-a** [comment]
https://www.nuget.org/packages/Cake.IntelliJ.Recipe/0.1.2 fixes the problem.

**Comment by nils-a** [comment]
#72 is only part of it. Reopen.
