### ISSUE TITLE
Add Cake script to "New Scratch file" menu

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake-rider#75]
I don't know if this is a job that the extension can do, but it would be great if the list that appears on the "New Scratch File" included an item for creating a Cake build script.

![image](https://user-images.githubusercontent.com/177608/106000524-4802ec00-6085-11eb-9141-d0c9a4996f02.png)

**Comment by nils-a** [comment]
also related to #55

**Comment by nils-a** [comment]
Probably something with [`com.intellij.scratch.rootType` and `com.intellij.scratch.creationHelper`](https://plugins.jetbrains.com/docs/intellij/extension-point-list.html#langextensionpointsxml)
