### ISSUE TITLE
Add Cake script to "Add" file menu

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake-rider#76]
Similar to #75, I'm not sure if this is a job that the extension can do, but it would be great if the list that appears on adding a new file included an item for creating a Cake build script.

![image](https://user-images.githubusercontent.com/177608/106000896-b47deb00-6085-11eb-9b94-a0f152acf6ff.png)

**Comment by nils-a** [comment]
probably related to #55, #75

**Comment by nils-a** [comment]
This was implemented in #106 as part of #55
