### ISSUE TITLE
Investigate what is necessary to publish a Rider extension

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-rider#8]
This will likely include creating a cake-build account, somewhere, that we can use for publishing the extension.

@anna-dolbina are you able to provide any insight here on exactly what is required?

Can the submission process be automated?

**Comment by nils-a** [comment]
We are officially listed now 🎉 
(The alpha version, anyhow..)

![image](https://user-images.githubusercontent.com/349188/103569289-55361c00-4ec7-11eb-9aa8-bc8f548bf4d7.png)

**Comment by nils-a** [comment]
Looking at this image: Should we set the display name to "Cake for Rider" that would  better match the "Cake for Visual Studio" Extension? (Then again, `Cake-VsCode` is named "Cake") @gep13 @pascalberger

**Comment by pascalberger** [comment]
`Cake Rider` sounds indeed a little bit strange to me. My vote goes to `Cake for Rider`

**Comment by gep13** [comment]
@nils-a I would agree with @pascalberger here.  Perhaps we can update the VsCode Extension on the next release?

**Comment by nils-a** [comment]
I think the investigation phase is complete. I am closing this issue in preparation of the 0.1.0 release.
